### PR TITLE
Add support for yaml files in export subcommand

### PR DESCRIPTION
**Pull request by Tomesco**
Adds exporting to yaml using [go-yaml/yaml](https://github.com/go-yaml/yaml). Follows same pattern as json exports. Includes simple tests.

### CODE REVIEW

**Comment by adrienkohlbecker** [comment]
This is really great, thanks for contributing! 
Small nit before I merge, would you mind updating the readme with the new option?

**Comment by Tomesco** [comment]
Updated readme and also some docs I missed initially. Also updated changelog and readme to v4.1.0 mentioning new feature.

**Comment by adrienkohlbecker** [comment]
Perfect! Releasing now

**Comment by adrienkohlbecker** [comment]
Done! https://github.com/adrienkohlbecker/ejson-kms/releases/tag/4.1.0 
Thanks again for contributing 🙏

**Pull request merged**
